"use strict";
const arr = ["Naran", "Clifton", 'Badshahi Mosque', "Dubai", "K-2"];
console.log(arr);
arr.sort();
console.log(arr);
let revList = arr.reverse();
console.log(revList);
console.log(arr);
let orderrevList = arr.reverse();
console.log(orderrevList);
arr.reverse();
console.log(arr);
arr.sort();
console.log(arr);
console.log(arr.reverse());
